<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AccountBooksTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('account_books')->delete();
        
        \DB::table('account_books')->insert(array (
            0 => 
            array (
                'id' => 1,
                'account_id' => 1,
                'account_type' => 'bank-account',
                'previous_balance' => 0.0,
                'open' => 1,
                'commission' => 0.0,
                'staff' => 0.0,
                'discount' => 0.0,
                'due' => 0.0,
                'deadline' => NULL,
                'balance_carry_forward' => NULL,
                'closing_balance' => 0.0,
                'closing_date' => NULL,
                'created_at' => '2024-04-30 15:57:12',
                'updated_at' => '2024-04-30 15:57:12',
            ),
            1 => 
            array (
                'id' => 2,
                'account_id' => 2,
                'account_type' => 'bank-account',
                'previous_balance' => 0.0,
                'open' => 1,
                'commission' => 0.0,
                'staff' => 0.0,
                'discount' => 0.0,
                'due' => 0.0,
                'deadline' => NULL,
                'balance_carry_forward' => NULL,
                'closing_balance' => 0.0,
                'closing_date' => NULL,
                'created_at' => '2024-04-30 15:58:08',
                'updated_at' => '2024-04-30 15:58:08',
            ),
            2 => 
            array (
                'id' => 3,
                'account_id' => 3,
                'account_type' => 'bank-account',
                'previous_balance' => 0.0,
                'open' => 1,
                'commission' => 0.0,
                'staff' => 0.0,
                'discount' => 0.0,
                'due' => 0.0,
                'deadline' => NULL,
                'balance_carry_forward' => NULL,
                'closing_balance' => 0.0,
                'closing_date' => NULL,
                'created_at' => '2024-04-30 15:58:31',
                'updated_at' => '2024-04-30 15:58:31',
            ),
            3 => 
            array (
                'id' => 4,
                'account_id' => 4,
                'account_type' => 'bank-account',
                'previous_balance' => 0.0,
                'open' => 1,
                'commission' => 0.0,
                'staff' => 0.0,
                'discount' => 0.0,
                'due' => 0.0,
                'deadline' => NULL,
                'balance_carry_forward' => NULL,
                'closing_balance' => 0.0,
                'closing_date' => NULL,
                'created_at' => '2024-04-30 15:59:26',
                'updated_at' => '2024-04-30 15:59:26',
            ),
            4 => 
            array (
                'id' => 5,
                'account_id' => 5,
                'account_type' => 'bank-account',
                'previous_balance' => 0.0,
                'open' => 1,
                'commission' => 0.0,
                'staff' => 0.0,
                'discount' => 0.0,
                'due' => 0.0,
                'deadline' => NULL,
                'balance_carry_forward' => NULL,
                'closing_balance' => 0.0,
                'closing_date' => NULL,
                'created_at' => '2024-04-30 15:59:45',
                'updated_at' => '2024-04-30 15:59:45',
            ),
            5 => 
            array (
                'id' => 6,
                'account_id' => 6,
                'account_type' => 'bank-account',
                'previous_balance' => 0.0,
                'open' => 1,
                'commission' => 0.0,
                'staff' => 0.0,
                'discount' => 0.0,
                'due' => 0.0,
                'deadline' => NULL,
                'balance_carry_forward' => NULL,
                'closing_balance' => 0.0,
                'closing_date' => NULL,
                'created_at' => '2024-04-30 15:59:56',
                'updated_at' => '2024-04-30 15:59:56',
            ),
            6 => 
            array (
                'id' => 7,
                'account_id' => 1,
                'account_type' => 'factory',
                'previous_balance' => 0.0,
                'open' => 1,
                'commission' => 0.0,
                'staff' => 0.0,
                'discount' => 0.0,
                'due' => 0.0,
                'deadline' => NULL,
                'balance_carry_forward' => NULL,
                'closing_balance' => 0.0,
                'closing_date' => NULL,
                'created_at' => '2024-04-30 16:00:23',
                'updated_at' => '2024-04-30 16:00:23',
            ),
            7 => 
            array (
                'id' => 8,
                'account_id' => 2,
                'account_type' => 'factory',
                'previous_balance' => 0.0,
                'open' => 1,
                'commission' => 0.0,
                'staff' => 0.0,
                'discount' => 0.0,
                'due' => 0.0,
                'deadline' => NULL,
                'balance_carry_forward' => NULL,
                'closing_balance' => 0.0,
                'closing_date' => NULL,
                'created_at' => '2024-04-30 16:00:40',
                'updated_at' => '2024-04-30 16:00:40',
            ),
            8 => 
            array (
                'id' => 9,
                'account_id' => 3,
                'account_type' => 'factory',
                'previous_balance' => 0.0,
                'open' => 1,
                'commission' => 0.0,
                'staff' => 0.0,
                'discount' => 0.0,
                'due' => 0.0,
                'deadline' => NULL,
                'balance_carry_forward' => NULL,
                'closing_balance' => 0.0,
                'closing_date' => NULL,
                'created_at' => '2024-04-30 16:01:00',
                'updated_at' => '2024-04-30 16:01:00',
            ),
            9 => 
            array (
                'id' => 10,
                'account_id' => 1,
                'account_type' => 'retail-store',
                'previous_balance' => 0.0,
                'open' => 1,
                'commission' => 0.0,
                'staff' => 0.0,
                'discount' => 0.0,
                'due' => 0.0,
                'deadline' => NULL,
                'balance_carry_forward' => NULL,
                'closing_balance' => 0.0,
                'closing_date' => NULL,
                'created_at' => '2024-04-30 16:01:29',
                'updated_at' => '2024-04-30 16:01:29',
            ),
            10 => 
            array (
                'id' => 11,
                'account_id' => 2,
                'account_type' => 'retail-store',
                'previous_balance' => 0.0,
                'open' => 1,
                'commission' => 0.0,
                'staff' => 0.0,
                'discount' => 0.0,
                'due' => 0.0,
                'deadline' => NULL,
                'balance_carry_forward' => NULL,
                'closing_balance' => 0.0,
                'closing_date' => NULL,
                'created_at' => '2024-04-30 16:01:48',
                'updated_at' => '2024-04-30 16:01:48',
            ),
            11 => 
            array (
                'id' => 12,
                'account_id' => 3,
                'account_type' => 'retail-store',
                'previous_balance' => 0.0,
                'open' => 1,
                'commission' => 0.0,
                'staff' => 0.0,
                'discount' => 0.0,
                'due' => 0.0,
                'deadline' => NULL,
                'balance_carry_forward' => NULL,
                'closing_balance' => 0.0,
                'closing_date' => NULL,
                'created_at' => '2024-04-30 16:02:06',
                'updated_at' => '2024-04-30 16:02:06',
            ),
            12 => 
            array (
                'id' => 13,
                'account_id' => 1,
                'account_type' => 'gift-supplier',
                'previous_balance' => 0.0,
                'open' => 1,
                'commission' => 0.0,
                'staff' => 0.0,
                'discount' => 0.0,
                'due' => 0.0,
                'deadline' => NULL,
                'balance_carry_forward' => NULL,
                'closing_balance' => 0.0,
                'closing_date' => NULL,
                'created_at' => '2024-04-30 16:02:42',
                'updated_at' => '2024-04-30 16:02:42',
            ),
            13 => 
            array (
                'id' => 14,
                'account_id' => 2,
                'account_type' => 'gift-supplier',
                'previous_balance' => 0.0,
                'open' => 1,
                'commission' => 0.0,
                'staff' => 0.0,
                'discount' => 0.0,
                'due' => 0.0,
                'deadline' => NULL,
                'balance_carry_forward' => NULL,
                'closing_balance' => 0.0,
                'closing_date' => NULL,
                'created_at' => '2024-04-30 16:03:05',
                'updated_at' => '2024-04-30 16:03:05',
            ),
        ));
        
        
    }
}